### ISSUE TITLE
OpenFold Singularity

### ISSUE THREAD

**Issue by gabrielctn** [aqlaboratory/openfold#126]
I try using a Singularity version of OpenFold to run on our cluster, since Docker is not secured for such environment.

I simply built the docker as described:
```
docker build -t openfold:1.0.0 .
```

then did:
```
singularity build openfold_1.0.0.sif docker-daemon:openfold:1.0.0
```

However, I face an issue when I run it:
```
singularity run openfold_1.0.0.sif python3 /opt/openfold/run_pretrained_openfold.py --help
```
I get:
```
Traceback (most recent call last):
  File "/opt/openfold/run_pretrained_openfold.py", line 34, in <module>
    from openfold.data import templates, feature_pipeline, data_pipeline
ImportError: cannot import name 'templates' from 'openfold.data' (unknown location)
```

Any idea how I can solve this ?
Thanks for your great tool !

**Comment by sachinkadyan7** [comment]
I am not familiar with Singularity setup, but this pretty much seems like a PYTHONPATH issue to me since the Python is not able to find the Openfold code files.

Insert a line in your execution script that adds the OPENFOLD directory to the PATH environment variable.
export OPENFOLD_DIR=<full path to Openfold Directory>
export PYTHONPATH=$PYTHONPATH:$OPENFOLD_DIR

If you provide more details about your system (OS, terminal you are using, etc), I can give you the exact commands.
