### ISSUE TITLE
How to train using openproteinset

### ISSUE THREAD

**Issue by hnisonoff** [aqlaboratory/openfold#258]
Would it be possible to get instructions on how to go from downloading `openproteinset` to training open fold using these MSAs? It seems that the instructions for the README involve computing MSAs from fasta files?

**Comment by gahdritz** [comment]
I'm surprised I never uploaded a script for this, since it's pretty involved. I'll put that on the docket.

Basically, in order to make it possible to download MSAs and template hits from the dataset separately, the AWS repo is structured as follows:

|__pdb # MSAs/template hits for every sequence in PDB (2021-12)
    |__<PDB_ID_1>
	  |__a3m
             |__bfd_uniclust_hits.a3m # BFD/Uniclust30 MSA by HHblits
             |__mgnify_hits.a3m # Mgnify MSA by JackHMMER
	     |__uniref90_hits.a3m # UniRef90 MSA by JackHMMER
	  |__hhr
	     |__pdb70_hits.hhr # PDB70 template hits by HHSearch

In order to train OpenFold on the data, you need to collapse the file format directories. In other words, the above structure should become:

|__pdb # MSAs/template hits for every sequence in PDB (2021-12)
    |__<PDB_ID_1>
       |__bfd_uniclust_hits.a3m # BFD/Uniclust30 MSA by HHblits
       |__mgnify_hits.a3m # Mgnify MSA by JackHMMER
       |__uniref90_hits.a3m # UniRef90 MSA by JackHMMER
       |__pdb70_hits.hhr # PDB70 template hits by HHSearch

"pdb" then becomes the "alignment_dir" argument passed to the training script. Do the same thing to the "uniclust30" directory on RODA to create the self-distillation set.

**Comment by gahdritz** [comment]
Update: there is actually a script for this: scripts/flatten_roda.sh

**Comment by hnisonoff** [comment]
Thanks!
