### ISSUE TITLE
About the memory

### ISSUE THREAD

**Issue by nnnwyn** [aqlaboratory/openfold#36]
Well done！I am quitly wondering that using 4 TITAN 2080 with 12G, can i train this model? will i meet the error on out of the memory?

**Comment by gahdritz** [comment]
You'll likely be able to train the model using the 256 crop size (which works on our 11GB 2080 Ti's). You'll probably need to keep the "clear_cache_between_blocks" option enabled in the extra MSA stack, which comes with a small performance hit. Training on the full finetuning settings, though (crops of size 384, extra MSAs of size 5120, etc.) is currently out of the question with just 12GB. We're working on fused or low-memory versions of components of the model, though, so that may change in the future.
