### ISSUE TITLE
Colab notebook breaks on first openfold import

### ISSUE THREAD

**Issue by vaclavhanzl** [aqlaboratory/openfold#398]
Running Colab with default settings (just changing the sequence to PDB's 6e5c). It stops with:
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-22d1f7254b4f> in <cell line: 47>()
     45 
     46 # A filthy hack to avoid slow Linear layer initialization
---> 47 import openfold.model.primitives
     48 
     49 def __default_linear_init__(self, *args, **kwargs):

ModuleNotFoundError: No module named 'openfold.model'
```
Looks like a broken setup of imports from Openfold - this is the first import from Openfold (but not the first import in general). I tried putting ```from openfold import config``` first and then it breaks on this as well - that particular hack being "filthy" is not the issue.

The previous Colab cell, ```Install third-party software```, runs through but prints:
```
Command 'cp -f /content/stereo_chemical_props.txt /usr/local/lib/python3.10/site-packages/openfold/resources/' returned non-zero exit status 1.
```
and it looks that ```/usr/local/lib/python3.10/site-packages/openfold/``` is missing entirely.

There is however a highly suspicious folder ```/usr/local/lib/python3.1/``` which makes me think that maybe the automatic python version changes tracking broke when going from '9' to '10', instead guessing '1'. However the variable ```python_version``` contains ```3.10```. (I'd propose to @jnwei to use this variable [here](https://github.com/aqlaboratory/openfold/blame/main/notebooks/OpenFold.ipynb#L127) to prevent future problems but it is not the problem now.)

That ```python3.1/``` is just a symlink to ```python3.10/```. No idea what made it.

**Comment by vaclavhanzl** [comment]
I tried to isolate the suspicious command and run it directly:
```
!pip install -q git+https://github.com/aqlaboratory/openfold.git@099769d2ecfd01a8baa8d950030df454a042c910
```
and I got:
```
  Preparing metadata (setup.py) ... done
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for openfold (setup.py) ... error
  ERROR: Failed building wheel for openfold
ERROR: Could not build wheels for openfold, which is required to install pyproject.toml-based projects
```
Maybe somebody can make some sense of it...

**Comment by jnwei** [comment]
Hi, thanks for raising this issue. 

As you noted in your second post, the breakage is due to colab's recent update to use CUDA 12, which requires the use of Pytorch2.  An update to pytorch 2 and all of openfold's dependencies is being developed now.

As a temporary fix to the notebook, you can try using @sokrypton's [fork of OpenFold](https://github.com/sokrypton/openfold). In that fork @sokrypton [changed the cuda flag compiler to use c++17 rather than c++14](https://github.com/aqlaboratory/openfold/compare/main...sokrypton:openfold:main).

Based on my quick testing, you'd also need to change the mamba install to:
`os.system(f"mamba install -y -c conda-forge -c bioconda kalign2=2.04 hhsuite=3.3.0 openmm=7.7.0 python={python_version} pdbfixer biopython=1.79")`

and the pip install to:
`os.system("pip install -q torch ml_collections py3Dmol modelcif")`

Maybe some of those packages are redundant, but with this I was able to get the imports to work again.

**Comment by jnwei** [comment]
Just a note that with the new v2, we updated the colab notebook and it should be running again. Please let me know if you find further issues with the notebook. Thanks!
