### ISSUE TITLE
I notice there is only instructions for a Linux Install, can I run this on my Windows laptop?

### ISSUE THREAD

**Issue by emilyrkang** [aqlaboratory/openfold#428]
OpenFold seems to be required for a different software I want to run: LigandMPNN, however it seems like there's an issue with my openfold install:

Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\LigandMPNN\openfold\np\protein.py", line 23, in <module>
    from openfold.np import residue_constants
  File "C:\LigandMPNN\openfold\np\residue_constants.py", line 24, in <module>
    import tree
ModuleNotFoundError: No module named 'tree'

**Comment by sachinkadyan7** [comment]
`tree` (or `dm-tree`) is a [Python utility package](https://pypi.org/project/dm-tree) we use to parse some dictionaries. Your error indicates that you don't have it installed. Make sure you go through the proper installation process, (`environment.yml` contains the software list and has `dm-tree` in the list) and you should get this package installed. Otherwise do:

```sh
pip install dm-tree
```

Other than that, in principle, you should be able to get this working on Windows too. Feel free to reopen if you face further issues.
